### ISSUE TITLE
I am a DAPP developer

### ISSUE THREAD

**Issue by MarsVinson** [bnb-chain/community-contributions#13]
Hello, I'm Mars, a DApp developer. I'd like to recommend our latest DApp game to Binance. How can I go about releasing my product on Binance's DApp store?
coo@greedyworld.io

**Comment by STdevK** [comment]
You can share your BSC dApp here https://dappbay.bnbchain.org/submit-dapp

**Comment by andres290487** [comment]
[][]
! []
<_>!!

**Comment by Foxsenrubas** [comment]
Спасибо
